// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Context;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240823015053_RemodeledUser")]
    partial class RemodeledUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Categories.Category", b =>
                {
                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Domain.Models.Categories.Subcategory", b =>
                {
                    b.Property<string>("SubcategoryId")
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .HasColumnType("text");

                    b.Property<string>("SubcategoryName")
                        .HasColumnType("text");

                    b.HasKey("SubcategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategory");
                });

            modelBuilder.Entity("Domain.Models.Clients.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClientRating")
                        .HasColumnType("integer");

                    b.Property<string>("ClientTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EventDetails")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusicGenre")
                        .HasColumnType("text");

                    b.Property<string>("PromotedPlace")
                        .HasColumnType("text");

                    b.Property<string>("SubcategoryId")
                        .HasColumnType("text");

                    b.Property<string>("Tiktok")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Youtube")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("YoutubeLinks")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("ClientId");

                    b.HasIndex("SubcategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Domain.Models.Prices.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriceId"));

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PriceTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PriceValue")
                        .HasColumnType("integer");

                    b.HasKey("PriceId");

                    b.HasIndex("ClientId");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("Domain.Models.Reviews.ExtendedReview", b =>
                {
                    b.Property<int>("ExtendedReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExtendedReviewId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FiveStar")
                        .HasColumnType("integer");

                    b.Property<int>("FourStar")
                        .HasColumnType("integer");

                    b.Property<int>("OneStar")
                        .HasColumnType("integer");

                    b.Property<int>("ThreeStar")
                        .HasColumnType("integer");

                    b.Property<int>("TwoStar")
                        .HasColumnType("integer");

                    b.HasKey("ExtendedReviewId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("ExtendedReview");
                });

            modelBuilder.Entity("Domain.Models.Reviews.RequestedReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateRequested")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewValue")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReviewId");

                    b.HasIndex("ClientId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestedReview");
                });

            modelBuilder.Entity("Domain.Models.Reviews.Review", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .HasColumnType("text");

                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewId")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewValue")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Domain.Models.Users.RequestedUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateAdded")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subcategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("RequestedUser");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FreeViewUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Privilege")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Domain.Models.Categories.Subcategory", b =>
                {
                    b.HasOne("Domain.Models.Categories.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Models.Clients.Client", b =>
                {
                    b.HasOne("Domain.Models.Categories.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId");

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("ClientsManaged")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Prices.Price", b =>
                {
                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithMany("Prices")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Models.Reviews.ExtendedReview", b =>
                {
                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithOne("ExtendedReview")
                        .HasForeignKey("Domain.Models.Reviews.ExtendedReview", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Domain.Models.Reviews.RequestedReview", b =>
                {
                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithMany("RequestedReviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany("RequestedReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Reviews.Review", b =>
                {
                    b.HasOne("Domain.Models.Clients.Client", "Client")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Categories.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("Domain.Models.Clients.Client", b =>
                {
                    b.Navigation("ExtendedReview");

                    b.Navigation("Prices");

                    b.Navigation("RequestedReviews");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Domain.Models.Users.User", b =>
                {
                    b.Navigation("ClientsManaged");

                    b.Navigation("RequestedReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
